version: "2"
services:
    app:
        build: ./app
        links:
          - db
        ports:
          - 5000:5000
        depends_on:
          - db     
        networks:
          - test        
    db:
        image: mysql
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: library
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
        networks:
          - test
        volumes:
          - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
  
networks:
  test:          
